
const APP_VERSION='1.4'; // v1.4: minimal negro, documentos por vencimiento y icono auto
const STORAGE_KEY='miAutoAlDiaData.v1';
const DEFAULT_IMG='vehicle_default.jpg';
const ENGINE_IMG='engine_bay_diagram.png';
const DEFAULT_ITEMS=[
  {id:'oil',name:'Aceite motor',category:'Motor',x:33,y:47,intervalKm:10000,intervalMonths:12},
  {id:'oil_filter',name:'Filtro de aceite',category:'Motor',x:37,y:51,intervalKm:10000,intervalMonths:12},
  {id:'air_filter',name:'Filtro de aire',category:'Motor',x:30,y:40,intervalKm:15000,intervalMonths:12},
  {id:'spark_plugs',name:'Bujías',category:'Motor',x:36,y:44,intervalKm:40000,intervalMonths:36},
  {id:'timing_belt',name:'Correa distribución',category:'Motor',x:25,y:50,intervalKm:60000,intervalMonths:60},
  {id:'coolant',name:'Refrigerante',category:'Motor',x:28,y:55,intervalKm:40000,intervalMonths:24},
  {id:'brake_fluid',name:'Líquido de frenos',category:'Motor',x:78,y:42,intervalKm:40000,intervalMonths:24},
  {id:'battery',name:'Batería',category:'Eléctrico',x:31,y:34,intervalKm:null,intervalMonths:36},
  {id:'tires',name:'Neumáticos',category:'Ruedas',x:65,y:75,intervalKm:null,intervalMonths:6},
  {id:'alignment',name:'Alineación y balanceo',category:'Ruedas',x:62,y:81,intervalKm:10000,intervalMonths:6},
  {id:'front_brakes',name:'Frenos delanteros',category:'Frenos',x:51,y:76,intervalKm:20000,intervalMonths:12},
  {id:'rear_brakes',name:'Frenos traseros',category:'Frenos',x:84,y:61,intervalKm:20000,intervalMonths:12},
  {id:'lights_front',name:'Luces delanteras',category:'Luces',x:14,y:57,intervalKm:null,intervalMonths:6},
  {id:'lights_rear',name:'Luces traseras',category:'Luces',x:94,y:37,intervalKm:null,intervalMonths:6},
  {id:'wipers',name:'Limpiaparabrisas',category:'Exterior',x:34,y:27,intervalKm:null,intervalMonths:12},
  {id:'driver_license',name:'Licencia de conducir',category:'Documentos',x:18,y:10,intervalKm:null,intervalMonths:null,document:true},
  {id:'driving_permit',name:'Permiso de conducción',category:'Documentos',x:38,y:10,intervalKm:null,intervalMonths:null,document:true},
  {id:'technical_review',name:'Revisión técnica',category:'Documentos',x:58,y:10,intervalKm:null,intervalMonths:null,document:true},
  {id:'soap',name:'SOAP',category:'Documentos',x:78,y:10,intervalKm:null,intervalMonths:null,document:true}
];
const CATEGORIES=['Todos','Motor','Ruedas','Frenos','Luces','Exterior','Documentos','Otros'];
const MOTOR_POINTS={
  oil:{x:14,y:63}, oil_filter:{x:52,y:50}, air_filter:{x:27,y:42}, spark_plugs:{x:62,y:25},
  timing_belt:{x:15,y:40}, battery:{x:82,y:27}, coolant:{x:84,y:58}, brake_fluid:{x:88,y:14},
  wipers:{x:32,y:10}
};
function categoryGroup(cat){cat=String(cat||'Otros').toLowerCase(); if(cat.includes('motor')||cat.includes('eléctr')||cat.includes('electr')||cat.includes('bater'))return 'Motor'; if(cat.includes('rueda')||cat.includes('neum')||cat.includes('aline'))return 'Ruedas'; if(cat.includes('freno'))return 'Frenos'; if(cat.includes('luz')||cat.includes('luces'))return 'Luces'; if(cat.includes('document'))return 'Documentos'; if(cat.includes('carro')||cat.includes('exterior')||cat.includes('limpia'))return 'Exterior'; return 'Otros';}
function itemsForCategory(){return mapCategory==='Todos'?data.items:data.items.filter(i=>categoryGroup(i.category)===mapCategory);}
function mapKey(){return mapCategory==='Motor'?'motor':'vehicle';}
function currentMapImage(){return mapCategory==='Motor'?ENGINE_IMG:(data.vehicle.image||DEFAULT_IMG);}
function pointFor(item){const key=mapKey(); const p=item.points&&item.points[key]; if(p&&typeof p.x==='number'&&typeof p.y==='number')return p; if(key==='motor'&&MOTOR_POINTS[item.id])return MOTOR_POINTS[item.id]; return {x:Number(item.x||50),y:Number(item.y||50)};}
function setPointFor(item,x,y){const key=mapKey(); if(key==='motor'){item.points={...(item.points||{}),motor:{x,y}};}else{item.x=x;item.y=y;item.points={...(item.points||{}),vehicle:{x,y}};}}
function categoryPills(forModal=false){return `<div class="cat-pills">${CATEGORIES.map(c=>`<button class="cat-pill ${mapCategory===c?'active':''}" onclick="${forModal?'setMapCategoryModal':'setMapCategory'}('${c}')">${c}</button>`).join('')}</div>`;}
function setMapCategory(cat){mapCategory=cat;render();}
function setMapCategoryModal(cat){mapCategory=cat;renderModal();}
function uid(){return (crypto.randomUUID?crypto.randomUUID():('id-'+Date.now()+'-'+Math.random().toString(16).slice(2)));}
function today(){return new Date().toISOString().slice(0,10);}
function money(n){return '$'+Number(n||0).toLocaleString('es-CL');}
function km(n){return Number(n||0).toLocaleString('es-CL')+' km';}
function daysBetween(a,b){const A=new Date(a+'T00:00:00'); const B=new Date(b+'T00:00:00'); return Math.round((B-A)/86400000);}
function addMonths(date, months){const d=new Date(date+'T00:00:00'); d.setMonth(d.getMonth()+Number(months||0)); return d.toISOString().slice(0,10);}
function defaultData(){return {app:'Mi Auto al Día',version:2,exportedAt:null,vehicle:{name:'Fiat Punto',year:'',plate:'',currentKm:0,image:DEFAULT_IMG},items:DEFAULT_ITEMS,records:[],settings:{appTitle:'Mi Auto al Día',warnDays:30,warnKm:1000}};}
let data=loadData();
let currentScreen='home';
let editingMap=false;
let dragId=null;
let studioOpen=false;
let studioEdit=true;
let studioZoom='zoom15';
let studioDragMoved=false;
let mapCategory='Todos';
let panStart=null;
function loadData(){try{const raw=localStorage.getItem(STORAGE_KEY); if(!raw)return defaultData(); return migrate(JSON.parse(raw));}catch(e){return defaultData();}}
function migrate(d){const base=defaultData(); d=d||{}; d.vehicle={...base.vehicle,...(d.vehicle||{})}; d.settings={...base.settings,...(d.settings||{})}; d.items=Array.isArray(d.items)&&d.items.length?d.items:base.items.map(i=>({...i})); d.records=Array.isArray(d.records)?d.records:[]; base.items.forEach(def=>{if(!d.items.some(i=>i.id===def.id))d.items.push({...def});}); d.items.forEach(i=>{if(typeof i.x!=='number')i.x=50;if(typeof i.y!=='number')i.y=50;if(!i.category)i.category='Otros'; if(!i.points)i.points={}; if(categoryGroup(i.category)==='Documentos'){i.document=true;i.intervalKm=null;i.intervalMonths=null;} }); const rn=id=>d.items.find(i=>i.id===id); if(rn('technical_review')){rn('technical_review').name='Revisión técnica'; rn('technical_review').document=true;} if(rn('soap')){rn('soap').name='SOAP'; rn('soap').document=true;} return d;}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
function toast(msg){const el=document.getElementById('toast'); el.textContent=msg; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2500);}
function itemById(id){return data.items.find(i=>i.id===id);}
function recordsFor(id){return data.records.filter(r=>r.itemId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||'') || (b.createdAt||'').localeCompare(a.createdAt||''));}
function lastRecord(id){return recordsFor(id)[0]||null;}
function isDocumentItem(item){return !!item?.document || categoryGroup(item?.category)==='Documentos';}
function statusFor(item){
  const rec=lastRecord(item.id);
  if(!rec)return {status:'unknown',label:'Sin dato',detail:isDocumentItem(item)?'Registra emisión y vencimiento':'Registra una mantención'};
  const now=today();
  if(isDocumentItem(item)){
    const exp=rec.expiryDate || rec.expirationDate || rec.expiresAt || '';
    if(!exp)return {status:'unknown',label:'Sin venc.',detail:'Falta fecha de vencimiento'};
    const left=daysBetween(now,exp);
    const detail='Vence '+formatDate(exp)+(rec.issueDate?(' · Otorgado '+formatDate(rec.issueDate)):'');
    if(left<0)return {status:'critical',label:'Vencido',detail};
    if(left<=Number(data.settings.warnDays||30))return {status:'warning',label:'Pronto',detail};
    return {status:'ok',label:'Vigente',detail};
  }
  let critical=false, warning=false, details=[];
  if(item.intervalMonths){const due=addMonths(rec.date,item.intervalMonths); const left=daysBetween(now,due); details.push('Fecha '+formatDate(due)); if(left<0)critical=true; else if(left<=Number(data.settings.warnDays||30))warning=true;}
  if(item.intervalKm && rec.km){const dueKm=Number(rec.km)+Number(item.intervalKm); const leftKm=dueKm-Number(data.vehicle.currentKm||0); details.push(km(dueKm)); if(leftKm<0)critical=true; else if(leftKm<=Number(data.settings.warnKm||1000))warning=true;}
  if(critical)return {status:'critical',label:'Crítico',detail:details.join(' · ')};
  if(warning)return {status:'warning',label:'Pronto',detail:details.join(' · ')};
  return {status:'ok',label:'Al día',detail:details.join(' · ')};
}
function summary(){const statuses=data.items.map(statusFor); return {ok:statuses.filter(s=>s.status==='ok').length, warning:statuses.filter(s=>s.status==='warning').length, critical:statuses.filter(s=>s.status==='critical').length, unknown:statuses.filter(s=>s.status==='unknown').length, spent:data.records.reduce((a,r)=>a+Number(r.cost||0),0)};}
function rank(st){return {critical:0,warning:1,unknown:2,ok:3}[st]??9;}
function go(screen){currentScreen=screen; render();}
function appBack(){ if(studioOpen){closeStudio(); return 'handled';} if(currentScreen!=='home'){go('home'); return 'handled';} return 'handled';}
window.appBack=appBack;
function header(sub='Control visual de mantenciones, fechas y kilometraje.') {return `<div class="top"><div><div class="brand">${escapeHtml(data.settings.appTitle||'Mi Auto al Día')}</div><div class="subtitle">${sub}</div></div><button class="iconbtn" onclick="go('settings')">⚙️</button></div>`}
function render(){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active')); document.getElementById(currentScreen).classList.add('active'); document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===currentScreen)); ({home:renderHome,register:renderRegister,items:renderItems,history:renderHistory,settings:renderSettings}[currentScreen])(); renderModal();}
function renderHome(){const s=summary(); const visible=itemsForCategory(); const ordered=visible.map(i=>({item:i,st:statusFor(i)})).sort((a,b)=>rank(a.st.status)-rank(b.st.status)); document.getElementById('home').innerHTML=`${header('Control minimalista negro, documentos y mantenciones críticas.')}
  <div class="stats"><div class="stat"><small>Críticos</small><strong>${s.critical}</strong></div><div class="stat"><small>Próximos</small><strong>${s.warning}</strong></div><div class="stat"><small>Al día</small><strong>${s.ok}</strong></div><div class="stat"><small>Km</small><strong>${shortKm(data.vehicle.currentKm||0)}</strong></div></div>
  <div class="panel"><div class="compact-title"><h2 class="section-title">Ver partes</h2><span class="category-count">${visible.length} visibles</span></div>${categoryPills(false)}<p class="compact-map-note">Elige una categoría para no llenar el auto de puntos.</p></div>
  ${renderCarMap('homeMap',false)}
  <div class="actions"><button class="bigbtn" onclick="go('register')">Registrar</button><button class="bigbtn alt" onclick="quickKm()">Actualizar km</button><button class="bigbtn soft" onclick="openStudio(false)">Mapa grande</button><button class="bigbtn soft" onclick="go('items')">Partes</button></div>
  <div class="panel"><div class="compact-title"><h2 class="section-title">Prioridad</h2><button class="small-action" onclick="go('items')">Ver todo</button></div><div class="urgent-strip">${ordered.slice(0,3).map(renderUrgentRow).join('')||'<div class="empty">Sin elementos en esta categoría</div>'}</div></div>`; bindMapEvents('homeMap',false);}
function renderCarMap(mapId='carMap', edit=false){const visible=itemsForCategory(); const showLabels=mapCategory!=='Todos'; const title=mapCategory==='Motor'?'Mapa del motor':'Mapa del auto'; return `<div class="panel"><div class="compact-title"><h2 class="section-title">${title}</h2><button class="small-action" onclick="openStudio(false)">Ampliar</button></div><p class="section-sub">Categoría: <b>${escapeHtml(mapCategory)}</b>. ${mapCategory==='Motor'?'Motor usa una imagen independiente para ubicar aceite, filtros, batería y líquido de frenos.':'En mapa grande puedes mover la imagen, hacer zoom, agregar o reubicar puntos.'}</p><div id="${mapId}" class="car-wrap ${showLabels?'show-labels':''} ${edit?'map-edit':''}"><img src="${currentMapImage()}" alt="Vehículo">${visible.map(i=>renderHotspot(i,showLabels)).join('')}</div><div class="legend"><span><i class="dot okdot"></i>Al día</span><span><i class="dot warndot"></i>Pronto</span><span><i class="dot baddot"></i>Crítico</span><span><i class="dot unkdot"></i>Sin dato</span></div></div>`}
function renderHotspot(i,showLabel=false){const st=statusFor(i).status; const p=pointFor(i);return `<button class="hotspot ${st}" style="left:${Number(p.x||50)}%;top:${Number(p.y||50)}%" data-id="${i.id}" title="${escapeHtml(i.name)}" aria-label="${escapeHtml(i.name)}">${showLabel?`<span class="hotspot-label">${escapeHtml(i.name)}</span>`:''}</button>`}
function renderUrgentRow(obj){const item=obj.item; const st=obj.st; return `<div class="urgent-row" onclick="openItem('${item.id}')"><div><b>${escapeHtml(item.name)}</b><br><span>${escapeHtml(st.detail||item.category||'')}</span></div><span class="badge ${st.status}">${st.label}</span></div>`}
function renderItemRow(obj){const item=obj.item||obj; const st=obj.st||statusFor(item); const rec=lastRecord(item.id); const recInfo=rec?(isDocumentItem(item)?`· ${rec.expiryDate?'vence '+formatDate(rec.expiryDate):'sin venc.'}`:`· ${formatDate(rec.date)} · ${rec.km?km(rec.km):'sin km'}`):'· sin registro'; return `<div class="item-card" onclick="openItem('${item.id}')"><div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(categoryGroup(item.category)||'')} ${recInfo}</p><p>${escapeHtml(st.detail||'')}</p></div><span class="badge ${st.status}">${st.label}</span></div>`}
function renderRegister(prefill=''){
  const opts=data.items.map(i=>`<option value="${i.id}" ${i.id===prefill?'selected':''}>${escapeHtml(categoryGroup(i.category))} · ${escapeHtml(i.name)}</option>`).join('');
  document.getElementById('register').innerHTML=`<div class="back-row"><button class="back" onclick="go('home')">←</button><h1 class="h1">Registrar</h1></div><div class="panel"><p class="section-sub">Mantenciones por fecha/km y documentos por fecha de vencimiento.</p><div class="field"><label>Elemento</label><select id="recItem" onchange="toggleRecordMode()">${opts}</select></div><div id="recordModeBox"></div><button class="save" onclick="saveRecord()">Guardar registro</button></div>`;
  toggleRecordMode();
}
function toggleRecordMode(){
  const item=itemById(val('recItem'));
  const box=document.getElementById('recordModeBox'); if(!box||!item)return;
  if(isDocumentItem(item)){
    box.innerHTML=`<div class="form-grid"><div class="field"><label>Fecha otorgado</label><input id="recDate" type="date" value="${today()}"></div><div class="field"><label>Fecha vencimiento</label><input id="recExpiry" type="date"></div></div><div class="form-grid"><div class="field"><label>Costo</label><input id="recCost" type="number" placeholder="Opcional"></div><div class="field"><label>Lugar / entidad</label><input id="recShop" placeholder="Municipalidad, PRT, aseguradora..."></div></div><div class="field"><label>Notas</label><textarea id="recNotes" placeholder="Ej: número de documento, patente, observaciones"></textarea></div>`;
  }else{
    box.innerHTML=`<div class="form-grid"><div class="field"><label>Fecha</label><input id="recDate" type="date" value="${today()}"></div><div class="field"><label>Kilometraje</label><input id="recKm" type="number" placeholder="Ej: 184500" value="${data.vehicle.currentKm||''}"></div></div><div class="form-grid"><div class="field"><label>Costo</label><input id="recCost" type="number" placeholder="Ej: 45000"></div><div class="field"><label>Taller / marca</label><input id="recShop" placeholder="Lubricentro, repuesto, etc."></div></div><div class="field"><label>Notas</label><textarea id="recNotes" placeholder="Ej: Aceite 10W40 + filtro"></textarea></div>`;
  }
}
function saveRecord(){
  const itemId=val('recItem'); const item=itemById(itemId);
  const r={id:uid(),itemId,date:val('recDate')||today(),km:Number(val('recKm')||0),cost:Number(val('recCost')||0),shop:val('recShop'),notes:val('recNotes'),createdAt:new Date().toISOString()};
  if(isDocumentItem(item)){r.issueDate=r.date; r.expiryDate=val('recExpiry')||''; r.km=0;}
  if(r.km>0)data.vehicle.currentKm=Math.max(Number(data.vehicle.currentKm||0),r.km);
  data.records.unshift(r); save(); toast(isDocumentItem(item)?'Documento guardado':'Mantención guardada'); go('home');
}
function renderItems(){const visible=itemsForCategory();let groups={}; visible.forEach(i=>{const g=categoryGroup(i.category);(groups[g]||(groups[g]=[])).push(i)}); const orderedGroups=Object.entries(groups).sort((a,b)=>CATEGORIES.indexOf(a[0])-CATEGORIES.indexOf(b[0])); document.getElementById('items').innerHTML=`<div class="back-row"><button class="back" onclick="go('home')">←</button><h1 class="h1">Partes</h1></div><div class="panel"><div class="compact-title"><h2 class="section-title">Categoría</h2><span class="category-count">${visible.length} partes</span></div>${categoryPills(false)}<div class="top-mini-actions"><button class="ghost" onclick="openStudio(false)">Mapa grande</button><button class="ghost" onclick="openStudio(true)">Editar puntos</button></div></div>${orderedGroups.map(([g,items])=>`<div class="panel"><div class="compact-title"><h2 class="section-title">${escapeHtml(g)}</h2><span class="badge unknown">${items.length}</span></div><div class="list">${items.map(i=>renderItemRow(i)).join('')}</div></div>`).join('')||'<div class="panel"><div class="empty">No hay partes en esta categoría.</div></div>'}`;}
function openItem(id){const item=itemById(id); if(!item)return; const st=statusFor(item); const recs=recordsFor(id); currentScreen='items'; document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active')); document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.go==='items')); const el=document.getElementById('items'); el.classList.add('active'); el.innerHTML=`<div class="back-row"><button class="back" onclick="go('items')">←</button><h1 class="h1">${escapeHtml(item.name)}</h1></div><div class="panel"><span class="badge ${st.status}">${st.label}</span><p class="section-sub" style="margin-top:12px">${escapeHtml(st.detail)}</p><div class="form-grid"><div class="stat"><small>Cada km</small><strong>${item.intervalKm?shortKm(item.intervalKm):'Manual'}</strong></div><div class="stat"><small>Cada meses</small><strong>${item.intervalMonths||'Manual'}</strong></div></div><button class="save" onclick="goRegister('${id}')">Registrar aquí</button><div class="toolbar"><button class="ghost" onclick="editItem('${id}')">Editar regla</button><button class="ghost" onclick="openStudio(true)">Editar punto en mapa</button></div><button class="danger-line" onclick="deleteItem('${id}')">Eliminar parte</button></div><div class="panel"><h2 class="section-title">Historial</h2><div class="list">${recs.map(renderRecord).join('')||'<div class="empty">Aún no tiene registros</div>'}</div></div>`; renderModal();}
function goRegister(id){go('register'); setTimeout(()=>{const e=document.getElementById('recItem'); if(e)e.value=id},0)}
function renderRecord(r){const item=itemById(r.itemId); const isDoc=isDocumentItem(item); const dateLine=isDoc?`${r.issueDate?('Otorgado '+formatDate(r.issueDate)):'Fecha '+formatDate(r.date)} · ${r.expiryDate?('Vence '+formatDate(r.expiryDate)):'sin vencimiento'}`:`${formatDate(r.date)} · ${r.km?km(r.km):'sin km'}`; return `<div class="item-card"><div><div class="record-date">${dateLine}</div><h3>${escapeHtml(item?item.name:'Elemento eliminado')}</h3><p>${r.cost?money(r.cost)+' · ':''}${escapeHtml(r.shop||'')} ${r.notes?'· '+escapeHtml(r.notes):''}</p></div><button class="badge unknown" onclick="deleteRecord('${r.id}')">Borrar</button></div>`}
function renderHistory(){const total=data.records.reduce((a,r)=>a+Number(r.cost||0),0); document.getElementById('history').innerHTML=`<div class="back-row"><button class="back" onclick="go('home')">←</button><h1 class="h1">Historial</h1></div><div class="stats"><div class="stat"><small>Registros</small><strong>${data.records.length}</strong></div><div class="stat"><small>Gasto</small><strong>${money(total)}</strong></div><div class="stat"><small>Partes</small><strong>${data.items.length}</strong></div><div class="stat"><small>Km</small><strong>${shortKm(data.vehicle.currentKm||0)}</strong></div></div><div class="toolbar"><button class="ghost" onclick="exportJson()">Exportar JSON</button><button class="ghost" onclick="exportCsv()">Exportar CSV</button></div><div class="panel"><div class="field"><label>Buscar</label><input id="search" placeholder="Aceite, taller, fecha..." oninput="renderHistoryList()"></div><div id="historyList" class="list"></div></div>`; renderHistoryList();}
function renderHistoryList(){const q=(document.getElementById('search')?.value||'').toLowerCase(); const rows=data.records.filter(r=>{const i=itemById(r.itemId); return [i?.name,r.date,r.shop,r.notes,String(r.km),String(r.cost)].join(' ').toLowerCase().includes(q)}); document.getElementById('historyList').innerHTML=rows.map(renderRecord).join('')||'<div class="empty">Sin resultados</div>';}
function renderSettings(){document.getElementById('settings').innerHTML=`<div class="back-row"><button class="back" onclick="go('home')">←</button><h1 class="h1">Ajustes</h1></div><div class="panel"><h2 class="section-title">Vehículo</h2><div class="field"><label>Nombre</label><input id="vehName" value="${escapeAttr(data.vehicle.name||'')}"></div><div class="form-grid"><div class="field"><label>Año</label><input id="vehYear" value="${escapeAttr(data.vehicle.year||'')}"></div><div class="field"><label>Patente</label><input id="vehPlate" value="${escapeAttr(data.vehicle.plate||'')}"></div></div><div class="field"><label>Kilometraje actual</label><input id="vehKm" type="number" value="${data.vehicle.currentKm||''}"></div><button class="save" onclick="saveVehicle()">Guardar vehículo</button></div><div class="panel"><h2 class="section-title">Imagen del auto</h2><p class="section-sub">Puedes usar tu foto del vehículo. Queda guardada en el respaldo JSON.</p><input type="file" id="carImageFile" accept="image/*" style="display:none" onchange="importCarImage(event)"><div class="toolbar"><button class="ghost" onclick="document.getElementById('carImageFile').click()">Cambiar imagen</button><button class="ghost" onclick="resetCarImage()">Imagen original</button></div></div><div class="panel"><h2 class="section-title">Respaldo</h2><p class="section-sub">Exporta o importa todo como JSON.</p><div class="toolbar"><button class="ghost" onclick="exportJson()">Guardar JSON</button><button class="ghost" onclick="shareJson()">Compartir JSON</button></div><input type="file" id="importFile" accept="application/json,.json" style="display:none" onchange="importJsonFile(event)"><button class="ghost" onclick="document.getElementById('importFile').click()">Importar JSON</button></div><div class="panel"><h2 class="section-title">Actualizaciones</h2><p class="section-sub">Versión instalada: <b>${nativeVersion()}</b></p><button class="ghost" onclick="checkUpdates()">Buscar actualizaciones</button><p id="updateBox" class="mini"></p></div><div class="panel"><h2 class="section-title">Zona peligrosa</h2><button class="danger-line" onclick="resetData()">Borrar datos locales</button></div>`}
function renderModal(){const root=document.getElementById('modalRoot'); if(!studioOpen){root.innerHTML='';return;} const visible=itemsForCategory(); root.innerHTML=`<div class="modal-backdrop"><div class="studio"><div class="studio-head"><h2>${mapCategory==='Motor'?'Motor ampliado':'Mapa ampliado'}</h2><button class="iconbtn" onclick="closeStudio()">✕</button></div><div class="studio-body"><p class="studio-help">Mueve la imagen con el dedo. Usa zoom y filtros por categoría. En Motor se usa una imagen propia del vano motor; el líquido de frenos queda a la derecha.</p>${categoryPills(true)}<div class="studio-actions"><button class="${studioEdit?'active':''}" onclick="studioEdit=true;renderModal()">Editar / agregar</button><button class="${!studioEdit?'active':''}" onclick="studioEdit=false;renderModal()">Solo revisar</button></div><div class="zoom-actions"><button class="${studioZoom===''?'active':''}" onclick="studioZoom='';renderModal()">1x</button><button class="${studioZoom==='zoom15'?'active':''}" onclick="studioZoom='zoom15';renderModal()">1.5x</button><button class="${studioZoom==='zoom20'?'active':''}" onclick="studioZoom='zoom20';renderModal()">2x</button></div><div class="view-actions"><button onclick="panStudio('front')">Frente</button><button onclick="panStudio('center')">Centro</button><button onclick="panStudio('rear')">Atrás</button></div>${studioEdit?'<div class="hint">Edición activa: toca un espacio vacío para crear punto. Mantén y arrastra un punto para moverlo. Toca un punto sin moverlo para editar nombre/categoría.</div>':'<div class="hint">Revisión: arrastra la imagen para moverte. Si hay muchos puntos, filtra por categoría.</div>'}<div class="map-scroll" id="mapScroll"><div id="studioMap" class="car-wrap studio-map show-labels ${studioZoom} ${studioEdit?'map-edit map-add-cursor':''}"><img src="${currentMapImage()}" alt="Vehículo">${visible.map(i=>renderHotspot(i,true)).join('')}</div></div><div class="legend"><span><i class="dot okdot"></i>Al día</span><span><i class="dot warndot"></i>Pronto</span><span><i class="dot baddot"></i>Crítico</span><span><i class="dot unkdot"></i>Sin dato</span></div></div></div></div>`; setTimeout(()=>{bindStudioMapEvents(); enableMapPan();},0);}
function openStudio(edit=true){studioOpen=true; studioEdit=!!edit; renderModal();}
function closeStudio(){studioOpen=false; renderModal(); render();}
function panStudio(where){const sc=document.getElementById('mapScroll'); if(!sc)return; const max=sc.scrollWidth-sc.clientWidth; const positions={front:0,center:.48,rear:1}; sc.scrollTo({left:Math.max(0,max*(positions[where]??.5)),behavior:'smooth'});}
function enableMapPan(){const sc=document.getElementById('mapScroll'); if(!sc)return; let active=false,startX=0,startY=0,left=0,top=0; sc.addEventListener('pointerdown',e=>{if(studioEdit)return; active=true; startX=e.clientX; startY=e.clientY; left=sc.scrollLeft; top=sc.scrollTop; sc.classList.add('drag-pan'); try{sc.setPointerCapture(e.pointerId)}catch(_){} }); sc.addEventListener('pointermove',e=>{if(!active||studioEdit)return; sc.scrollLeft=left-(e.clientX-startX); sc.scrollTop=top-(e.clientY-startY);}); sc.addEventListener('pointerup',e=>{active=false; sc.classList.remove('drag-pan');}); sc.addEventListener('pointercancel',()=>{active=false; sc.classList.remove('drag-pan');}); setTimeout(()=>{if(sc.scrollWidth>sc.clientWidth)panStudio('center')},80);}
function bindMapEvents(mapId='homeMap', edit=false){const map=document.getElementById(mapId); if(!map)return; map.querySelectorAll('.hotspot').forEach(dot=>{dot.addEventListener('click',e=>{e.stopPropagation(); openItem(dot.dataset.id);});});}
function bindStudioMapEvents(){const map=document.getElementById('studioMap'); if(!map)return; const pos=(clientX,clientY)=>{const rect=map.getBoundingClientRect(); return {x:Math.max(2,Math.min(98,((clientX-rect.left)/rect.width)*100)),y:Math.max(2,Math.min(98,((clientY-rect.top)/rect.height)*100))};}; const move=(clientX,clientY)=>{if(!studioEdit||!dragId)return; const item=itemById(dragId); if(!item)return; const p=pos(clientX,clientY); const old=pointFor(item); if(Math.abs(Number(old.x)-p.x)>0.15||Math.abs(Number(old.y)-p.y)>0.15)studioDragMoved=true; setPointFor(item,p.x,p.y); const dot=map.querySelector(`[data-id="${dragId}"]`); if(dot){dot.style.left=p.x+'%';dot.style.top=p.y+'%';}};
  let lastTap=0; map.addEventListener('click',e=>{if(!studioEdit)return; if(e.target.closest('.hotspot'))return; const p=pos(e.clientX,e.clientY); createItemAt(p.x,p.y);});
  map.addEventListener('dblclick',e=>{e.preventDefault(); studioZoom=studioZoom===''?'zoom15':(studioZoom==='zoom15'?'zoom20':''); renderModal();});
  map.querySelectorAll('.hotspot').forEach(dot=>{dot.addEventListener('pointerdown',e=>{if(!studioEdit)return; e.preventDefault(); e.stopPropagation(); studioDragMoved=false; dragId=dot.dataset.id; dot.setPointerCapture(e.pointerId);}); dot.addEventListener('pointermove',e=>move(e.clientX,e.clientY)); dot.addEventListener('pointerup',e=>{e.stopPropagation(); const id=dragId; if(id){save(); dragId=null; if(!studioDragMoved)editPointBasic(id); else toast('Punto movido'); studioDragMoved=false;}}); dot.addEventListener('click',e=>{e.preventDefault(); e.stopPropagation(); if(!studioEdit)openItem(dot.dataset.id);});});}
function createItemAt(x,y){const name=prompt('Nombre de la parte'); if(!name)return; const category=prompt('Categoría: Motor, Ruedas, Frenos, Luces, Documentos, Exterior u Otros', mapCategory==='Todos'?'Otros':mapCategory)||'Otros'; let kmv='',mv=''; const isDoc=categoryGroup(category)==='Documentos'; if(!isDoc){kmv=prompt('Intervalo en km. Vacío = manual',''); mv=prompt('Intervalo en meses. Vacío = manual','');} const item={id:uid(),name:name.trim(),category:category.trim(),x:50,y:50,points:{},intervalKm:kmv?Number(kmv):null,intervalMonths:mv?Number(mv):null,document:isDoc}; setPointFor(item,x,y); data.items.push(item); save(); toast('Punto creado'); renderModal();}
function editPointBasic(id){const item=itemById(id); if(!item)return; const name=prompt('Nombre de la parte', item.name); if(name===null)return; const category=prompt('Categoría: Motor, Ruedas, Frenos, Luces, Documentos, Exterior u Otros', categoryGroup(item.category)||'Otros'); if(category===null)return; item.name=name.trim()||item.name; item.category=category.trim()||item.category||'Personalizado'; save(); toast('Parte actualizada'); renderModal();}
function saveVehicle(){data.vehicle.name=val('vehName');data.vehicle.year=val('vehYear');data.vehicle.plate=val('vehPlate');data.vehicle.currentKm=Number(val('vehKm')||0);save();toast('Vehículo guardado');go('home');}
function quickKm(){const n=prompt('Kilometraje actual',data.vehicle.currentKm||''); if(n===null)return; data.vehicle.currentKm=Number(String(n).replace(/[^0-9]/g,'')); save(); render();}
function editItem(id){const item=itemById(id); if(!item)return; const name=prompt('Nombre', item.name); if(name===null)return; const category=prompt('Categoría', item.category||''); if(category===null)return; item.name=name.trim()||item.name; item.category=category.trim()||'Otros'; if(categoryGroup(item.category)==='Documentos'){item.document=true; item.intervalKm=null; item.intervalMonths=null;}else{const kmv=prompt('Intervalo en km. Vacío = manual', item.intervalKm||''); if(kmv===null)return; const mv=prompt('Intervalo en meses. Vacío = manual', item.intervalMonths||''); if(mv===null)return; item.document=false; item.intervalKm=kmv?Number(kmv):null; item.intervalMonths=mv?Number(mv):null;} save(); openItem(id);}
function addCustomItem(){const name=prompt('Nombre de la parte'); if(!name)return; const category=prompt('Categoría: Motor, Ruedas, Frenos, Luces, Documentos, Exterior u Otros', mapCategory==='Todos'?'Otros':mapCategory)||'Otros'; data.items.push({id:uid(),name:name.trim(),category:category.trim(),x:50,y:50,intervalKm:null,intervalMonths:null,document:categoryGroup(category)==='Documentos'}); save(); openStudio(true);}
function deleteItem(id){const item=itemById(id); if(!item)return; if(recordsFor(id).length && !confirm('Esta parte tiene historial. Si la eliminas, sus registros quedarán como elemento eliminado. ¿Continuar?'))return; if(!confirm('¿Eliminar '+item.name+'?'))return; data.items=data.items.filter(i=>i.id!==id); save(); toast('Parte eliminada'); go('items');}
function deleteRecord(id){if(!confirm('¿Borrar este registro?'))return; data.records=data.records.filter(r=>r.id!==id); save(); render();}
function importCarImage(ev){const file=ev.target.files[0]; if(!file)return; if(file.size>2500000 && !confirm('La imagen es pesada y hará crecer el respaldo JSON. ¿Usarla igual?'))return; const fr=new FileReader(); fr.onload=()=>{data.vehicle.image=fr.result; save(); toast('Imagen guardada'); go('home');}; fr.readAsDataURL(file);}
function resetCarImage(){data.vehicle.image=DEFAULT_IMG; save(); toast('Imagen original restaurada'); go('home');}
function exportPayload(){return JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2);}
function exportJson(){const name='mi-auto-respaldo-'+today()+'.json'; const json=exportPayload(); if(window.AndroidBridge?.saveJson)AndroidBridge.saveJson(name,json); else download(name,json,'application/json');}
function shareJson(){const name='mi-auto-respaldo-'+today()+'.json'; const json=exportPayload(); if(window.AndroidBridge?.shareJson)AndroidBridge.shareJson(name,json); else download(name,json,'application/json');}
function exportCsv(){const header=['fecha','elemento','categoria','km','costo','taller','notas']; const rows=data.records.map(r=>{const i=itemById(r.itemId)||{}; return [r.date,i.name||'',i.category||'',r.km||'',r.cost||'',r.shop||'',r.notes||''].map(csvCell).join(',')}); const csv=header.join(',')+'\n'+rows.join('\n'); if(window.AndroidBridge?.saveCsv)AndroidBridge.saveCsv('mi-auto-historial-'+today()+'.csv',csv); else download('mi-auto-historial.csv',csv,'text/csv');}
function importJsonFile(ev){const file=ev.target.files[0]; if(!file)return; const fr=new FileReader(); fr.onload=()=>{try{const parsed=migrate(JSON.parse(fr.result)); if(!Array.isArray(parsed.items)||!Array.isArray(parsed.records))throw new Error('Formato inválido'); data=parsed; save(); toast('Respaldo importado'); go('home');}catch(e){alert('No se pudo importar: '+e.message)}}; fr.readAsText(file);}
function resetData(){if(!confirm('Esto borrará los datos locales de la app. ¿Continuar?'))return; localStorage.removeItem(STORAGE_KEY); data=defaultData(); save(); go('home');}
function checkUpdates(){const box=document.getElementById('updateBox'); if(box)box.textContent='Buscando...'; if(window.AndroidBridge?.checkGithubUpdates)AndroidBridge.checkGithubUpdates(); else if(box)box.textContent='Disponible solo en APK.';}
window.onNativeUpdateResult=function(res){const box=document.getElementById('updateBox'); if(!box)return; if(!res||!res.ok){box.textContent='No se pudo revisar: '+(res?.error||'error');return;} box.innerHTML=`Última: <b>${escapeHtml(res.tagName||res.name||'')}</b><br><button class="ghost" onclick="AndroidBridge.openUpdateUrl('${escapeAttr(res.apkUrl||res.htmlUrl)}')">Abrir descarga</button>`}
function nativeVersion(){try{return window.AndroidBridge?.getVersionName?.()||APP_VERSION}catch(e){return APP_VERSION}}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csvCell(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function val(id){return document.getElementById(id)?.value||''}
function formatDate(d){if(!d)return''; const parts=String(d).slice(0,10).split('-'); if(parts.length!==3)return d; return `${parts[2]}-${parts[1]}-${parts[0]}`}
function shortKm(n){n=Number(n||0); if(n>=1000)return Math.round(n/1000)+'k'; return String(n)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s){return escapeHtml(s)}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.go));
render();
